### ISSUE TITLE
The recommended parameters for ONT PromethION

### ISSUE THREAD

**Issue by flystar233** [tjiangHIT/cuteSV#1]
Could  you provide the recommended parameters for ONT PromethION？

**Comment by tjiangHIT** [comment]
Hello flystar233,

Sorry for omiting the description of analysis of ONT datasets. I current version of cuteSV (1.0.3), you can just use the default setting of parameters to process the ONT PromethION sorted bam.

At present, for processing the PacBio CLR and ONT Promethon datasets, the parameters settings are the same. It is mainly due to their high sequencing errors.  I have set them as default.

But for PacBio CCS data, since its outstanding sequencing quality, cuteSV adopt another specific setting and you can find these values from the description (cuteSV -h).

Thanks for using cuteSV, pls post your questions without hesitation.

Tao
