### ISSUE TITLE
Minor error in bed file for TRA simulation

### ISSUE THREAD

**Issue by LYC-vio** [tjiangHIT/cuteSV#109]
in sim_tra.bed:
```
15	102478998	102578998	reciprocal translocation	h1:19:93730:reverse:reverse	0
```
however, the length of chr15 inhs37d5 (downloaded from  ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/technical/reference/phase2_reference_assembly_sequence/hs37d5.fa.gz) was 102531392. which was smaller than 102578998

VISOR will thus throw an error message saying that "Line 130: column 3 (chromosome end) contains an invalid coordinate (greater than chromosome end)"

```
4	36380	136380	reciprocal translocation	h1:13:115100237:forward:forward	0
```
length of chr13 was 115169878, which was smaller than 115100237+100000

VISOR will thus throw an error message saying that "Line 227: column 5 (variant information) breakpoint coordinate lies outside chromosome (greater than chromosome end)"

**Comment by tjiangHIT** [comment]
Hello @LYC-vio,

Thanks for pointing this out.
As you know, the records used in our sim_tra.bed file were from a published dataset. Some translocation records might be not suitable for the reference genome due to the brute-force rule (i.e., breakpoint + 100000). Fortunately, Visor (we used version) would ignore these records and kindly report some warnings, then would discard them in our final benchmarks. Hence, these records would not affect our evaluation.
Thank you again for your attention on cuteSV.

Best regards!
Tao

**Comment by LYC-vio** [comment]
Thank you Tao!
I just manually fixed these TRA records:
changed
15	102478998	102578998	reciprocal translocation	h1:19:93730:reverse:reverse	0
to
15	102478998	102531392	reciprocal translocation	h1:19:93730:reverse:reverse	0

changed
4	36380	136380	reciprocal translocation	h1:13:115100237:forward:forward	0
to
4	36380	106000	reciprocal translocation	h1:13:115100237:forward:forward	0

**Comment by LYC-vio** [comment]
by the way, just in case anyone else need to debug this kind of [issue](https://github.com/davidebolo1993/VISOR/issues/31#issue-1521106989)
