### ISSUE TITLE
Skipping most contigs/reads

### ISSUE THREAD

**Issue by danielwood1992** [tjiangHIT/cuteSV#115]
Hello, 

I am using cuteSV (v 2.0.0, but v.2.0.2 and 1.0.13 also have the same issue) using a sorted bam file generated using minimap2 with ONT data at about ~15X coverage and a genome with ~2,000 contigs.  The STDERR indicates about 80% of contigs are skipped entirely, with 8% being called and the remaining 12% (which includes scaffolds making up ~95% of the genome) not present in the STDERR (although they are in the vcf output header) with default settings, or those recommended with ONT data. This results in a very small number of putative SVs. Do you know what might be causing so many of the contigs to be skipped, particularly the very large ones?

Thanks a lot and best wishes,

Daniel Wood

**Comment by tjiangHIT** [comment]
Hello @danielwood1992,

Thank you for pointing out this issue.

Before answering your question, please let me explain when the contigs will be skipped.

cuteSV parallelly detects SV signatures on different contigs (through the task division module) and stores these signatures in LIST. If the length of the LIST is 0, that is, there is no SV signature here, and cuteSV will output a message that the corresponding contig is skipped.

Regarding your question, there are lots of contigs ignored, in other words, cuteSV did not discover any signatures in those contigs. Due to the data having only about 15X, please check the parameter like supporting read, decrease it to 2 or 3 and run cuteSV again.

Hope this can help you!
Best,
Tao

**Comment by danielwood1992** [comment]
Dear Tao,

Thanks a lot for your response. I have ended up solving this issue by removing ; and = symbols from my contig names in my bam/fasta file - this seems to produce a much more normal looking vcf file, so I assume one of those was interfering in some way.

Best wishes,

Daniel Wood

**Comment by tjiangHIT** [comment]
Hello @danielwood1992,

Glad to hear this exciting news!
And feel free to contact me here if have any questions.

Best regards,
Tao
