### ISSUE TITLE
Translocations BND meaning. Inversions also?

### ISSUE THREAD

**Issue by ViriatoII** [tjiangHIT/cuteSV#13]
Hello again,

I have small questions about translocations.  Look at the following example (I'm still using 1.0.7, but I think it doesn't matter for the question):

`NC_024459.2     115467803       cuteSV.BND.54   N       ]NC_024463.2:150593897]N        .       PASS    PRECISE;SVTYPE=BND;CHR2=NC_024463.2;END=150593897;RE=118;RNAMES=m64093_191209_130050/78512469/ccs_63,m64093_191209_130050/3606801/ccs_64,m64093_191209_130050/154338485 <clipped all read names out here> GT:DR:DV:PL:GQ  ./.:.:118:.,.,.:.
`

So, this translocation comes from NC_024459.2 at position 115467803 to NC_024463.2 at position 150593897? Or the otherway around? What does this notation:
> ]NC_024463.2:150593897]N 

 exactly mean? Specifically I mean the "]" sign before the contig name and "]N" afterwards.

Another question is: Are inversions identifiable? Are they noted as translocations with the same chromossome and inverted coordinates?

Kind regards,
Ricardo

**Comment by tjiangHIT** [comment]
Hello @ViriatoII 

**For Q1**, a brief description about breakends is below, you can find the corresponding explanation:
> An arbitrary rearrangement event can be summarized as a set of novel adjacencies. Each adjacency ties together
2 breakends. The two breakends at either end of a novel adjacency are called mates.
> There is one line of VCF (i.e. one record) for each of the two breakends in a novel adjacency. A breakend record is
identified with the tag “SYTYPE=BND” in the INFO field. The REF field of a breakend record indicates a base or
sequence s of bases beginning at position POS, as in all VCF records. The ALT field of a breakend record indicates
a replacement for s. This “breakend replacement” has three parts:
> 1. The string t that replaces places s. The string t may be an extended version of s if some novel bases are inserted
during the formation of the novel adjacency.
> 2. The position p of the mate breakend, indicated by a string of the form “chr:pos”. This is the location of the
first mapped base in the piece being joined at this novel adjacency.
> 3. The direction that the joined sequence continues in, starting from p. This is indicated by the orientation of
square brackets surrounding p.

> These 3 elements are combined in 4 possible ways to create the ALT. In each of the 4 cases, the assertion is that s
is replaced with t, and then some piece starting at position p is joined to t. The cases are:

|REF| ALT| Meaning|
| :------------ |:---------------|:-------------|
|s| t[p[| piece extending to the right of p is joined after t|
|s| t]p]| reverse comp piece extending left of p is joined after t|
|s| ]p]t| piece extending to the left of p is joined before t|
|s| [p[t| reverse comp piece extending right of p is joined before t|

More details and examples please see the 5.4 section of [here](https://samtools.github.io/hts-specs/VCFv4.2.pdf).

**For Q2**, cuteSV just uncovers inversions in the same chromosome and reports them as INV instead of BND or TRA. Moreover, in the current version of cuteSV only detects translocations that occur in two different chromosomes and all translocations discovered are recorded as BND.

Best,
Tao

**Comment by ViriatoII** [comment]
Great answers, thanks! 

So to make it clear, in:

> NC_024459.2 115467803 cuteSV.BND.54 N ]NC_024463.2:150593897]N . PASS PRECISE;SVTYPE=BND;CHR2=NC_024463.2;END=150593897

-  NC_024459.2 receives an inverted translocation at start position 115467803 (going backwards).   
-  CHR2 is where the translocation comes from.  
-  END(150593897) is where the translocation ends in CHR2 (but where does it start?).  

So finally, what is the length of the translocation?

**Comment by tjiangHIT** [comment]
Hello @ViriatoII 
This is an example:

>  NC_024459.2  ====A=====a><b=====B====
>  NC_024463.2 <c=========C=========d>

We know that the end position _a_ (NC_024459.2:115467803) of contig A connects to the end position _d_ (NC_024463.2:150593897) of contig C. Please check the next breakend in NC_024459.2 that adjacent to the location _a_ (e.g. occurs at position _b_, _a_ and _b_ should be very close to each other). If you find the breakend that the start position _b_ of contig B is connected to the start position _c_ of contig C, the complete inverted translocation can be inferred:
- The start position in NC_024463.2 is _c_
- The possible translocation length is _d-c_

Best,
Tao
