### ISSUE TITLE
Only one type of SV in the output (SVTYPE=BND)

### ISSUE THREAD

**Issue by andreyurch** [tjiangHIT/cuteSV#2]
Dear developers,

I used cuteSV with oxford nanopore data (coverage 6.5x, nmglr aligner). My aim was to identify inversions from 4Mbp to 25Mbp . I received many potential results, but they all were with the same SV type :  SVTYPE=BND  What doest it mean? My code is below. Thank you!

cuteSV -t 10 -l 1000000 -L 1000000 -b 500000000 --min_support 3 --max_cluster_bias_INS 100 \
--diff_ratio_merging_INS 0.2 --diff_ratio_filtering_INS 0.6 \
--diff_ratio_filtering_DEL 0.7 BAM \
BAM.vcf BAM_folder

**Comment by tjiangHIT** [comment]
Hello @andreyurch.

Sorry for replying late.

In current version of cuteSV, it can discover SVs from 30bp to 100kbp considering the limitation of read length. As a result, you didn't get other type of SVs larger than 1Mbp besides BND.

My question is: what is your average read length in using?
If the length is pretty good, I can relax the limitation of 10kbp and make it potential for your practice.

Thanks for your use and feedback!

Tao

**Comment by andreyurch** [comment]
Dear Tao, 

The average read length we have is 6kb.  Do you mean that the inversion size should be less than the read length?

Thanks!
Andrey

**Comment by tjiangHIT** [comment]
Hello @andreyurch 
CuteSV can detect inversions longer than the read length. 
I modified the relevant code to form a specific version for you. Due to the limitation of currently working conditions, I can't release this version at this time because I haven't tested it on a large scale data. I hope you can provide your email address so that I can send it to you.
Tao.

**Comment by andreyurch** [comment]
Dear Tao,

Thank you very much!  Please send me it to andreyurch@gmail.com
