### ISSUE TITLE
The evaluation of SVs

### ISSUE THREAD

**Issue by jane13-cs** [tjiangHIT/cuteSV#20]
There is a question about the evaluation of SV results: For example, on my simulated data, I use minimap2+SVIM to predict SV calls, and then use SURVIVOR to evaluate and find that the recall is always around 0.42?

**Comment by tjiangHIT** [comment]
Hello @jane13-cs 

I am sorry that cannot give some points for this, because I have never used SURVIVOR to generate simulated long-read datasets and evaluated for this.
In my practice, I used VISOR that developed by @davidebolo1993 to perform simulation study and assessed these data by my [in-house script](https://github.com/tjiangHIT/cuteSV/tree/master/src/benchmarks/eval_sim.py).
You can see some demos in my [repository](https://github.com/tjiangHIT/cuteSV/tree/master/simulation) as a reference to try your simulated study.
For your relative low recall rate in your practice, I think there might be some inappropriate parameters setting in your workflow.
I will be happy to work with you to figure out this problem if you can share some more detailed messages.

Best,
Tao

**Comment by davidebolo1993** [comment]
Hi @tjiangHIT and @jane13-cs,

For what it's worth, feel free to get in touch if needed.

Best,

Davide

**Comment by jane13-cs** [comment]
Hi @tjiangHIT ,
I used VISOR to successfully generate simulation data, for example, "VISOR LASeR -g reference_genome.fasta -s donor_genome_del -bed LASeR.bed -o data_del_5x -c 5 --threads 16 --noaddtag", and then used the generated sim.srt.bam to call SV, such as svim, "svim alignment sim_del_5x-svim ～/sim.srt.bam ～/ref/human_hs37d5.fasta --min_sv_size 30" to get the vcf result, then how should I evaluate the result?
I tried to convert "sim_del.bed" to "sim_del.vcf", then bgzip and tabix, and then use truvari to evaluate the results, such as "truvari bench -b sim_del.vcf.gz -c svim-variant.vcf.gz -r human_hs37d5.fasta -o output_dir/", but the final result is TP=0?

**Comment by tjiangHIT** [comment]
Hello @jane13-cs ，

Please use the [script](https://github.com/tjiangHIT/cuteSV/blob/master/src/benchmarks/eval_sim.py) to evaluate the simulated data.
More details, run the command below for each specific type of SV data:
> For DEL/INV/INS data
python3 eval_sim.py IID sim_del/ins/inv.bed LASeR.bed cuteSV.vcf sniffles.vcf pbsv.vcf svim.vcf
> For DUP data
python3 eval_sim.py IID sim_dup.bed LASeR.bed cuteSV.vcf sniffles.vcf pbsv.vcf svim.vcf
> For BND data
python3 eval_sim.py IID sim_tra.bed LASeR.bed cuteSV.vcf sniffles.vcf pbsv.vcf svim.vcf

As you know, the design of this script just to benchmark the results of simulation in my paper. I strongly suggest you are able to adjust it in order to satisfy your assessment requirement. If you have problems about how to rewrite the evaluation script, please contact with me via tjiang@hit.edu.cn.

Best, 
Tao

**Comment by jane13-cs** [comment]
Hi @tjiangHIT ,

Thanks, it helps me a lot.
When I run pbsv on simulated data, such as "pbsv discover alns/sim_del_5x/sim.srt.bam sim_del_5x.svsig.gz --tandem-repeats ref/human_hs37d5.trf.bed", I get the error:
"-|- FATAL -|- Run -|- 0x7f25c6a43740|| -|- pbsv discover ERROR: [pbbam] BAM header ERROR: read group ID not found:"
Have you ever encountered this situation? Do you use "samtools view -h"?

**Comment by davidebolo1993** [comment]
Hi @jane13-cs,

VISOR does not provide RG ID in the simulated BAM,  as most tools do not even need it for downstream analysis. I'll see if I can add this in the next release.
For the time being, I think this can be fixed by samtools addreplacerg (see samtools specs for details)

**Comment by davidebolo1993** [comment]
BTW, something like the command line below should work:

```bash
samtools addreplacerg -r '@RG\tID:Nanopore\tSM:Bulk' -o sim.withRD.srt.bam sim.srt.bam && samtools index sim.withRD.srt.bam
```

**Comment by tjiangHIT** [comment]
Hello @jane13-cs,

Please add **-s** parameter (i.e. a string) when running _pbsv discover_. This option will override sample name tag from BAM read group.
Good luck!

Tao

**Comment by jane13-cs** [comment]
hello @tjiangHIT , @davidebolo1993 ,

Thank you so much for your suggestions about read group ID！
When I add -s parameter  to run pbsv discover , another error shows "-|- FATAL -|- Run -|- 0x7f18736eb740|| -|- pbsv discover ERROR: Hard clips are not supported."

**Comment by jane13-cs** [comment]
Hello @tjiangHIT , @davidebolo1993 ,

Thank you so much for your suggestions about read group ID！
When I add -s parameter  to run pbsv discover , another error shows "-|- FATAL -|- Run -|- 0x7f18736eb740|| -|- pbsv discover ERROR: Hard clips are not supported."

**Comment by tjiangHIT** [comment]
Hello @jane13-cs,

You should add **-Y** parameter when running minimap2, that is, you need to modify the commands of implementation of minimap2, just like:
https://github.com/tjiangHIT/VISOR/blob/e8752d34c99af86faeed726cbece32ae23a742d0/VISOR/LASeR/LASeR.py#L536 
https://github.com/tjiangHIT/VISOR/blob/e8752d34c99af86faeed726cbece32ae23a742d0/VISOR/LASeR/LASeR.py#L544
Hope this helps!

Tao

**Comment by jane13-cs** [comment]
Hello @tjiangHIT ,

When I use VISOR downloaded from https://github.com/tjiangHIT/VISOR.git, the sim.srt.bam  has no available read alignments (small profile). VISOR has been installed correctly (including the depended libraries), also I have tried the different versions of samtools(samtools-1.5,samtools-1.7,samtools1.9).

**Comment by tjiangHIT** [comment]
Hello @jane13-cs,

I have updated the VISOR (https://github.com/tjiangHIT/VISOR.git) and modified the commands for minimap2.
Please git clone the latest version of it and rerun the simulation.
Best,
Tao
