### ISSUE TITLE
Question about calling INV

### ISSUE THREAD

**Issue by Jingwen7** [tjiangHIT/cuteSV#31]
Hi @tjiangHIT, 

Thanks for developing cuteSV! It's really nice to have more options of SV caller!
I have a question about calling INV. I run alignment by lra (a long read aligner), but cannot call INV at this site. In IGV, there is clearly an inversion there. Do you have any idea what is causing that? For a read containing an inversion, it would be split into 3 alignments in SAM output. Is there any specific output order of those 3 alignments in order to call INV? Or could the primary/supplementary flag influence this? Since there are 3 alignments, only one of them gets the primary flag, the rest two are supplementary. I'm just guessing if which one gets primary/supplementary flag will influence the calling of INV. Any help is deeply appreciated!!
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/35582642/110562852-26266b80-80ff-11eb-8400-41f3dbb10452.png">

Best,
Jingwen

**Comment by tjiangHIT** [comment]
Hello @Jingwen7,

Thanks for pointing this out. 

cuteSV detects the inversion through split read alignment with different strands. That is, it firstly selects the partial read with the primary flag. Then cuteSV collects the other partial reads with the supplementary flag through the SA tag in the primary alignment.  After that, cuteSV will reorganize these split reads according to their coordinates both on read and reference. And an inversion signature will be reported when one partial read has a contrary strand compared with others.

As you see it, cuteSV only scans read-alignments with the primary flag and collects the supplementary alignments information through the SA tag, rather than looks through the alignments with the supplementary flag. I suspect that's why missing this inversion. As for which alignment should be specified as the primary, I feel it does not affect the detection of INV.
In a word, it will have great potential if the primary alignment contains the SA field with complete supplementary information.

Congratulations on developing the LRA aligner and look forward to it will become a powerful tool in frontier research.

Best,
Tao

**Comment by Jingwen7** [comment]
Hi Tao,

Thanks for your quick response! I didn't know cuteSV analyzes the split read through SA tag. I find there is a bug in lra when generating SA tag. After fixing it, things work fine! :)

Best,
Jingwen

**Comment by tjiangHIT** [comment]
Hello Jingwen,

I'm glad to hear that. 
Feel free for talking more about SV calling. 

Best,
Tao
