### ISSUE TITLE
consulting about parameter settings on low depth ONT data

### ISSUE THREAD

**Issue by yekaizhou** [tjiangHIT/cuteSV#32]
Hi,

I used the pipeline listed on https://github.com/tjiangHIT/sv-benchmark to detect ~8X ONT data of HG002, and evaluated using truvari and GIAB Tier1 truth-set.

Although the precision was high (~0.94), it can only call total ~6000 INSs and DELs, and the recall was relatively low (~0.1).

I was following all the pipeline listed on mentioned website, except that I used current version cuteSV (1.0.10), used the input of the original 27G 8X HG002 sequencing data on (https://ftp.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG002_NA24385_son/UCSC_Ultralong_OxfordNanopore_Promethion/GM24385_1.fastq.gz), used minimap without MD tag, and used cuteSV with the hs37d5 reference.

I noticed that cuteSV version in this benchmark test was 1.0.3, so I am wondering if the version transition made the inner parameter setting changed, so that the performance on low depth gets lower? In this case how can I adjust the parameters to enhance low depth ONT mode? 

Otherwise, was there something wrong with my workflow that dampened the results? Maybe because of the MD tag and the input reference genome?

**Comment by tjiangHIT** [comment]
Hello @yekaizhou,

Thank you for pointing this out.
I think you need to adjust the parameter of _**--min_support**_ or _**-s**_ when you using data with different coverage.
This parameter represents the minimum number of reads that support an SV to be reported. 
For 8X data, I recommend applying _**-s 2**_ in order to sensitively discover much more SVs.

Best,
Tao
