### ISSUE TITLE
cuteSV on assembly: no DUP or BND

### ISSUE THREAD

**Issue by GuillaumeHolley** [tjiangHIT/cuteSV#36]
Hi,

I have run cuteSV in "assembly mode" following the instructions of the [wiki](https://github.com/tjiangHIT/cuteSV/wiki/Diploid-assembly-based-SV-detection-using-cuteSV). My input assembly is the [CHM13](https://github.com/marbl/CHM13) v1.0 assembly from the T2T consortium aligned to the reference genome GRCh38.p13. Since the CHM13 assembly is only from one haplotype, I did not haplotag the BAM file.

The VCF file I obtained from cute SV contained no break ends (and hence no translocations) and contained only one duplication on chrM. Is that expected behavior?

Thank you for the help.
Guillaume

**Comment by tjiangHIT** [comment]
Hello @GuillaumeHolley,

Thanks for pointing this out.
I have run cuteSV with the data you mentioned and reproduced the same results.
The main reason for only 1 duplication and no translocation is using the default value of **_--max_split_parts_** (i.e., -p 7), which means skipping the alignments containing over 7 split segments. 
Since the more split segments in each assembly-based alignment, we adjusted the parameter **_--max_split_parts_** to take all split segments into account on each alignment when using -p -1.
With **_-p -1_**, cuteSV is able to discover more SVs (especially for INV, DUP, BND) through assembly-based alignments.
Please apply the latest version of cuteSV for a new trial.
Hope this helps.

Tao
