### ISSUE TITLE
Run VISOR LASeR using --noaddtag [Suggestion] 

### ISSUE THREAD

**Issue by davidebolo1993** [tjiangHIT/cuteSV#4]
Hi @tjiangHIT,

it seems that you are using [VISOR](https://github.com/davidebolo1993/VISOR) for your simulations. JFYI, you can speed things up by enforcing VISOR LASeR to skip haplotype and clone tagging of the generated BAM files if you do not need such informations in the final BAM (simply ignore this if you need the HP and CL tags). Something like:
``` bash
VISOR LASeR -g reference_genome.fasta -s donor_genome_del -bed LASeR.bed -o data_del_5x -c 5 --threads 16 --noaddtag
```
This prevents VISOR to spend time in re-parsing the BAM files generated, which can be time-consuming for high coverages. 
Good luck with your tool !

Best,

Davide

**Comment by tjiangHIT** [comment]
Hi @davidebolo1993, 
Thank you for pointing this out. I have update the commands in simulation using.
VISOR is an excellent simulation tool and easy to implement in my project. In my repository, I added --MD and -Y into the Minimap2 running commands in order to generate more universal BAM to support SV callers (e.g. Sniffles and PBSV) with specific needs. This modification is necessary not only for me but also for other users to implement comparative experiments. Hope you can add this and other parameters for some specific requirements and make VISOR more versatile.

Thank you again!

Best,

Tao

**Comment by davidebolo1993** [comment]
Hi @tjiangHIT,

Done ! (https://github.com/davidebolo1993/VISOR/issues/6) 

Best,

Davide
