### ISSUE TITLE
Reversed start and end of BND

### ISSUE THREAD

**Issue by charliechen912ilovbash** [tjiangHIT/cuteSV#45]
If the start and end of two BND, i.e. translocation, are reversed, does it means they are actually the same translocation event?
E.g.

```
id            start                end
TRA-1:   chr1,         1,    chr2,   100
TRA-2:   chr2,   100,   chr1,         1  
```

**Comment by tjiangHIT** [comment]
Hello @charliechen912ilovbash,

Sorry for taking so long to reply to you.
Due to my negligence, I did not notice this problem. 
For your question, I think it is just the same breakpoint rather than the same event.
For an instance as below：
>a =======><------------ b
>c ------------><======= d
A translocation that a and c are connected has the same breakpoint combination with the translocation that a and d are connected. However, these two translocations are different apparently.

Hope this can help you.
Best,
Tao
