### ISSUE TITLE
populaton genotyping  of Diploid assembly

### ISSUE THREAD

**Issue by Chenglin20170390** [tjiangHIT/cuteSV#87]
Hi JiangTao,

we are doing SV calling for haplotype resolved genome
After simulation, we found cuteSV-asm was best for us to detect SV and genotype. (https://github.com/tjiangHIT/cuteSV/wiki/Diploid-assembly-based-SV-detection-using-cuteSV)

<img width="765" alt="截屏2022-05-20 下午1 09 13" src="https://user-images.githubusercontent.com/33062118/169454837-c50fd411-910c-43b6-bb8e-93fc94253ad4.png">

We would like to call SV of  29 diploid genome by cuteSV-asm, in this case, we conside the population genotying of this population. Do you have any suggestion for  population genotyping based on  cuteSV-asm ?
 For population genoptyping of ccs reads, I saw the previous issure that we can use SURVIVOR to merge SV and genotyping with -Ivcf.  So, is it also working for cuteSV-asm? How about the phased genotyping of population?

**Comment by tjiangHIT** [comment]
Hello @Chenglin20170390,

Thank you for evaluating the performance of cuteSV and reporting the results to us, this will give a brief view for the users and help them in the selection of tools properly.

For your questions:
1. In order to generate haplotype-resolved SVs, we recommend adding haplotype-unique tags first. And then complete contigs mapping, and SV calling. Please refer to steps 4 to 8 [here](https://github.com/tjiangHIT/cuteSV/wiki/Diploid-assembly-based-SV-detection-using-cuteSV). After that, you will acquire the phased genotypes.
2. The population-based SV calling is not only suitable for ccs reads but for cuteSV-asm. You can follow these stages shown below:
s1 For each of the 29 samples, please finish the haplotype-resolved SVs calling described in 1. So you will get 29 vcf files.
s2 Integrate these 29 callsets into a population-based one through one of SURVIVOR, Truvari, Jasmine, etc.
s3 Perform cuteSV force-calling for the contigs alignments of each sample all under the population-based vcf file.
s4 Finally, merge the 29 re-genotyped callsets into a final file via SURVIVOR or Bcftools. So far you can estimate the allele frequency of each SV precisely.

Hope this can help you.
Best regards,
Tao

**Comment by Chenglin20170390** [comment]
Hi Tao, 
   many thanks for your quick response, it's really help me a lot.

  After calling haplotype resolved sample, I found some INVs have roughly same start postion with different length for same haplotype.
for example:
```
chr01	6405298	cuteSV.INV.0	T	<INV>	11.8	PASS	SVTYPE=INV;SVLEN=11010048;END=17415346;RE=1;RNAMES=cutesvh2_H2_chr1	GT	0/1
chr01	6407527	cuteSV.INV.1	T	<INV>	11.8	PASS	SVTYPE=INV;SVLEN=3007047;END=9414574;RE=1;RNAMES=cutesvh2_H2_chr1	GT	0/1
```
here show a screenshot of bam  of  this  region
<img width="866" alt="inv" src="https://user-images.githubusercontent.com/33062118/169592566-bb326ef4-5389-4dec-9a73-07a5b22a6378.png">

**Comment by tjiangHIT** [comment]
Hello @Chenglin20170390,

From your example, I guess there is a nested-SV that might be a dup-inv or inv-dup.
I draw a plot based on these two provided inversions as below.

![issue87](https://user-images.githubusercontent.com/7637156/169632879-0c88ed25-150a-469f-bc8b-ef0d91e3f0c8.png)

In general,
1. There is an inverted segment marked as 2 was detected as the first inversion_1: 6405298-17415346;
2. There is another inverted segment marked as 3 that was discovered as the second inversion_2: 6407527-9414574.
Please manually check them.

Best regards,
Tao

**Comment by Chenglin20170390** [comment]
thanks Tao,  do you have any suggestion about how to check  this inversion?
I have pick up the bam region of chr01:1-20000000 and visulize with pafplot.  In the synteny dot plot,  it's look like  normal sitation.
```
samtools view -h   01_bam/C001.cuteSV.bam chr01:1-20000000> target.region.sam
paftools.js sam2paf target.region.sam >target.paf
pafplot  target.paf -s 10000  --png target.png
```
<img width="409" alt="image" src="https://user-images.githubusercontent.com/33062118/169647945-98e672b2-cb3e-4e53-a7b6-6087e4888acb.png">

```
minimap2     VN:2.24-r1122  
cuteSV 1.0.13
```

**Comment by tjiangHIT** [comment]
Hello @Chenglin20170390,

From the image, Paftools seems not to exhibit a nested-SV. 
Could you share the target.region.sam file to me in order to further check these variants?
If possible, please send it to my mail (tjiang _AT_ hit _DOT_ edu _DOT_ cn) and tell the reference genome version.

Thank you in advance,
Tao

**Comment by Chenglin20170390** [comment]
> Hello @Chenglin20170390,
> 
> From the image, Paftools seems not to exhibit a nested-SV. Could you share the target.region.sam file to me in order to further check these variants? If possible, please send it to my mail (tjiang _AT_ hit _DOT_ edu _DOT_ cn) and tell the reference genome version.
> 
> Thank you in advance, Tao
sent it, please check,   thanks

**Comment by tjiangHIT** [comment]
Hello @Chenglin20170390,

I have received your mail and then analyzed it by myself. Actually, these two SVs are not INVs and might be two mobile elements caused by DNA rearrangement. Please see the info shown below:
![list](https://user-images.githubusercontent.com/7637156/170393120-397ff64d-5af2-4c36-9342-16c9290095f6.png)
The description of each column are:
1. Read_start: the starting coordinate on the read;
2. Read_end: the end coordinate on the read;
3. Ref_start: the starting coordinate on the reference genome;
4. Ref_end: the end coordinate on the reference genome;
5. Chr: the chromosome ID;
6. Strand: the orientation.

I listed a few possible mobile elements here which are circled in red rectangles. 
Because cuteSV generated SV call through the nearest two non-collinear segments, cuteSV will report some extremely large-size SVs (e.g., INV, DEL, DUP, BND, INS) in these regions.
In order to remove those mutations that look plausible but are actually fake, you can clean the callsets through hard filtering on SV size. 
Usually, I recommend discarding the SVs longer than 100 kbp when using read-alignment input. As for the assembly-alignment input, you can select a more large threshold.
Hope this can help you.

Best regards,
Tao

**Comment by Chenglin20170390** [comment]
Dear Tao,

       Thanks for your  patient explanation.  That's helpfull.

Best,
Lin Cheng
