### ISSUE TITLE
A lot of false positive insertions reported by cuteSV

### ISSUE THREAD

**Issue by lxwgcool** [tjiangHIT/cuteSV#92]
Hi, 

We plan to use cuteSV to build our in-house structure variation pipeline for pacbio HIFI reads. I am current doing the benchmark to evaluate the performance of different SV callers by using HG002. 

I have a question about the insertion detected by cuteSV .
We found that many of these insertions are not supported by any reads when we use IGV to check their alignment situation (even the vcf shows many reads support these events).  

For example, 
There is an insertion reported by CuteSV:
chr1    1087029 cuteSV.INS.61   C       CGCCAAAAGGGGGGGGGGGGGGGGGGGGGGAGGGGGGTGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGTGGTGAT      67.6    PASS    PRECISE;SVTYPE=INS;SVLEN=121;END=1087029;CIPOS=-1090,1090;CILEN=-63,63;RE=21;RNAMES=NULL;AF=0.4038      GT:DR:DV:PL:GQ  0/1:31:21:68,0,163:67

Here is the alignment results shown in IGV:
![image](https://user-images.githubusercontent.com/11053933/178829306-1f9f83ab-d7f6-4aaa-a07c-7768eee34151.png)

You can see there are no reads support this insertion around "1087029" (shown in IGV).

Actually there are a lot of insertions (not deletion) reported by CuteSV have this issue. 

Back to the strategy of our benchmark:
We applied CuteSV to 3 different BAM files. These BAM files are from the same HG002 pacbio HIFI reads but generated by different mapping tools, including minimap2, pbmm2 and NGMLR. The "CuteSV + minimap2" performance relatively normal (compare with other SV callers). However the "CuteSV + pbmm2" and "CuteSV + NGMLR" preform pretty bad compare with other SV callers (e.g. pbsv and sniffles). 

One of the major reason is that CuteSV  reports much larger number of insertions (SVTYPE=INS and FILTER=PASS) compared with other SV callers. For example other callers report around 16000 insertions, however CuteSV reports 50000 insertions (SVTYPE=INS and FILTER=PASS) for the same sample + same aligner. I think the case I described above is the major reason for this low performance (these cases cause a pretty low precision (FP, recall is good), which decreased the F1 score significantly).

Could you help me understand why there are so many these cases occur (insertion reported by cuteSV, but no reads support it in IGV)?  Is there anyway to reduce the number of FP in call set? 

I also attached vcf  file generated by cuteSV. Please check it.
[StdReads.HG002.MD.sorted.5.cuteSV.refined.zip](https://github.com/tjiangHIT/cuteSV/files/9105965/StdReads.HG002.MD.sorted.5.cuteSV.refined.zip)

The coverage of our HG002 BAM is around 30x, and the reads we used are from pacbio HIFI reads.

Thanks so much for your help.

**Comment by Meltpinkg** [comment]
Hello, @lxwgcool 

I've thought about the question you reported and I feel confused, too. In our experiment on cuteSV, we haven't met such similar events. We have tested several datasets of HG002 before and haven't discovered a similar insertion as you mentioned.

To solve this event, could you provide part of your data if it is available for us to check it? Because only the bam generated from pbmm2 and NGMLR has this problem, you can extract either of them. For the output SV above, you can extract the reads around the SV breakpoint by the commands like
`samtools view {bam} -h -b -o check.bam chr1:1077029-1097029`

It will be of great help for us to look into the error. Please send the check.bam to me via [sakura_qian@163.com](mailto:sakura_qian@163.com) 
Thanks in advance.

Best,
Shuqi

**Comment by lxwgcool** [comment]
Dear Shuqi, 

Thanks so much for your prompt reply. Sure I will attach the BAM in this thread. I also have some additional comments. Please check the details below.

* All insertions mentioned below are filtered by "SVTYPE=INS and FILTER=PASS".

1: Regarding the length of insertions, I just did a statistic. Please check the screenshot below:

<img width="926" alt="Capture_number_differt_len" src="https://user-images.githubusercontent.com/11053933/179056738-38e7315d-0211-4f88-98fa-c51f6f3389d8.PNG">

You can see: 
The number of  INS with LEN < 50   :  4982
The number of  INS with LEN < 100 :  35955
The number of  INS with LEN < 150 :  42465
Total number of INS                          :  49251

Based on the statistical result above, I think the length of the insertion (121) as I mentioned yesterday is longer than most of insertions in call set. 

2: Different Insertion cases and it's BAM file.

(1)  Case 1: PRECISE  SVTYPE=INS  SVLEN=121  END=1087029
This is the case I mentioned yesterday. 
Issue: no reads support this event in IGV.
There is the BAM & BAI of this INS.
[INS_1087029_LEN_121.tar.gz](https://github.com/tjiangHIT/cuteSV/files/9114504/INS_1087029_LEN_121.tar.gz)

(2) Case 2: PRECISE  SVTYPE=INS  SVLEN=231  END=1021390
In this case, the length if INS is 231. 
Issue: no reads support this event in IGV.
There is the BAM & BAI of this INS.
```
samtools view {bam} -h -b -o check.bam chr1:1020390-1022390
```
[INS_1021390_LEN_231.tar.gz](https://github.com/tjiangHIT/cuteSV/files/9114553/INS_1021390_LEN_231.tar.gz)

(3) Case 3: PRECISE  SVTYPE=INS  SVLEN=1266  END=811165
In this case, the length if INS is 1266, which is pretty long.
Issue: we do find some INS around 811400. However the position of this INS is marked as 811165 by cuteSV (no INS events around this position), which is significantly far away from the position where this event occur in IGV. Just wonder how to understand this difference? 
Pleas check the screenshot below:

![image](https://user-images.githubusercontent.com/11053933/179062424-d401134b-ef34-48bb-95ae-1666955e9810.png)

There is the BAM & BAI of this INS.
```
samtools view {bam} -h -b -o check.bam chr1:809165-813165
```
[INS_811165_LEN_1266.tar.gz](https://github.com/tjiangHIT/cuteSV/files/9114637/INS_811165_LEN_1266.tar.gz)

(4) Case 4: PRECISE  SVTYPE=INS  SVLEN=893  END=1318103
In this case, the length if INS is 893  , which is pretty long as well.
Issues: 
   * we do find some INS around 1318103. However the length of these insertion are 1426, 503, 401, 90, 73, 508 and etc in IGV. Just wonder why the length of this INS be calculated as 893 by cuteSV? 
   * In addition we do find many insertions with length around 1395 at position 138000 in IGV. Just wonder why this event do not be reported by cuteSV?

Pleas check the screenshot below:

![image](https://user-images.githubusercontent.com/11053933/179065405-75e8ce0f-2351-4a2e-bffd-f744624a2a78.png)

There is the BAM & BAI of this INS.
```
samtools view {bam} -h -b -o check.bam chr1:1317103-1319103
```
[INS_1318103_LEN_893.tar.gz](https://github.com/tjiangHIT/cuteSV/files/9114715/INS_1318103_LEN_893.tar.gz)

Finally, the reference we used is hg19, and you can find all my running details (cuteSV) in the head of vcf I attached yesterday. 

Thanks so much for your help
Best
Xin

**Comment by Meltpinkg** [comment]
Hi, @lxwgcool 

Thanks for providing the data. I tested cuteSV on four bam file above. 

For the first two examples, I ran cuteSV with the command as it is shown in the vcf:
`cuteSV INS_1087029_LEN_121/check_1087029.bam hg19.fa 121.vcf sigs121/ --threads 12 --genotype --min_support 5 --max_cluster_bias_INS 1000 --diff_ratio_merging_INS 0.9 --max_cluster_bias_DEL 1000 --diff_ratio_merging_DEL 0.5` 
  and there're 7 SVs reported:
![image](https://user-images.githubusercontent.com/47966870/179228986-46a4fb34-53f8-4226-9699-a97abf3a3f14.png)
The results shows that there doesn't exist a corresponding SV at position 1087029.

For the second example, the command is shown below:
`cuteSV INS_1021390_LEN_231/check_1021390.bam hg19.fa 231.vcf sigs231/ --threads 12 --genotype --min_support 5 --max_cluster_bias_INS 1000 --diff_ratio_merging_INS 0.9 --max_cluster_bias_DEL 1000 --diff_ratio_merging_DEL 0.5`
  and the three SV reported 
![image](https://user-images.githubusercontent.com/47966870/179228884-0b954b44-5faa-4974-bd6c-166770ad79be.png)

Also, there is not an SV around 1021390.
Therefore, in my conclusion, for the first two example, cuteSV won't report such inexistent insertion. And for these two cases, I thought about two possibilities:
1. You can check the nersion of cuteSV, in my experiment I use the newest version on cuteSV's GitHub. You can git clone the newest cuteSV and test the cases.
2. Another possibility is the insertion doesn't come from the provided bam because of some unexpected error. You can add a parameter '--report_readid', which will declare the reads which support the SVs in the output vcf. And then we can focus on these reads to get further check.  

In general, if the newest version of cuteSV still reports these two insertions, you can try to run cuteSV with '--report_readid' as it is mentioned above. And check the INFO field which contains 'RNAMES=', it shows the reads that support the SV. And you can check these supporting reads in IGV. Also, if possible, you can provide the output insertions information and the corresponding reads in bam for me to check it too.

And then, for the last two examples, we can see that there are several insertion signatures around the SV. Considering the erroneous sequencing, cuteSV combines them and reported a representative SV. So the position of SV deviates from which we see in IGV. You can decrease the value of '--diff_ratio_merging_INS' to make the combination more strict. In our experiment, when decreasing the parameter to 0.3, both of the SV can be reported correctly.

Best,
Shuqi

**Comment by lxwgcool** [comment]
Dear Shuqi,

Sorry for the delay. Thanks so much for your prompt reply. We are using the version cuteSV-1.0.13. I have checked cuterSV github page, and I think it should be the latest version released by your team. 

I have some comments for the issues we discussed in the last threads.

(1) Regarding the insertion "1087029" and "1021390" in chromosome 1:

It is for sure that cuteSV cannot find these two insertions based on the region-level BAM attached in previous threads. This is because the regions I extracted is too short. However, it does not mean the results from cuteSV is inconsistent. If we give a longer region for testing, I believe these 2 FP insertions could be reported by cuteSV. Based on my experience of the SV Caller (I used to design an algorithm call "EigenDel" to find deletions by using illumina short reads), the algorithm may use both local vision (e.g. signal close to events) and global vision (signal from the neighbors, some mapping results far away from current events (e.g. repeats)) to detect SV events. 

In order to verify if the larger region could give us the identical results, I extracted the whole chorm1 mapping results from the original BAM, and then run the cuteSV by using this chr1-only bam with the additional option you suggested "--report_readid". 

Please check the SV call set below generated from cuteSV:
[StdReads.HG002.MD.sorted.5.cuteSV.chr1.zip](https://github.com/tjiangHIT/cuteSV/files/9146619/StdReads.HG002.MD.sorted.5.cuteSV.chr1.zip)
 
Both insertions, including "1087029" and "1021390", are contained by this call set. Please check the details from these two insertions below: 
![image](https://user-images.githubusercontent.com/11053933/179860969-49d76ac1-7683-4800-8832-26845e66f4f0.png)

The size of Chrom1 is around 12GB. Please let me know if you need this bam for reproducing these 2 FP insertions & how I share it with you. Since this BAM comes from the public HG002, there is no security issue from my end. 

(2) Regarding  the option "'--diff_ratio_merging_INS"
Thank you so much for the tips.  I noticed that the default value of "diff_ratio_merging_INS" for "PacBio CCS(HIFI) data" is 0.9 (0.3 for the case of " PacBio CLR data" and "ONT data").  May I know if there is any instruction/rule/tip I can follow to set this value? In addition, may I know why "0.9" was set as the default value of "PacBio CCS(HIFI) data" while other two cases were set as "0.3". 

Thanks you so much for your help. 
Best regards
Xin

**Comment by lxwgcool** [comment]
Hi Shuqi,

I just cooperated with our HPC admin and uploaded the 12GB BAM file into the BOX. I think you should already received the invite link of this BAM file through email (sakura_qian@163.com).

Please let me know if you need anything else.
Thanks again for your help
Best
Xin

**Comment by Meltpinkg** [comment]
Dear Xin,

Thanks so much for providing the data. It gives me a lot of help on this problem.

First, I'd like to draw my conclusion that the problem is about the different parameters that cuteSV sets for different sequencing dataset. The parameter **max_cluster_bias** and **diff_ratio_merging** are set for merging the variation signatures from alignment together to generate the precise SV. Taking the features of different sequencing technologies into account, we set different default parameters. It can be found that the parameters set for "Hifi(CCS) data" are always larger than "PacBio CLR data" and "ONT data", because the sequencing error rate of Hifi data is much smaller than the other two, which makes the variation signatures more regular. So in our opinion this parameter will give out the best result.

Then, let's see the two examples. Regarding the insertion "1087029" in chromosome 1:
I extracted a larger region of IGV around this position. The insertions from the red circle lead to the report of this insertion. And cuteSV collects these signatures and chooses the **median** of them to represent the insertion, which is shown as 1087029.
![image](https://user-images.githubusercontent.com/47966870/180405180-6e9afa17-a020-4573-8c84-e206c60224e3.png)
As this region is not as neat as we thought, it depends on our judgement on an SV. If we think for this situation shown in IGV, it is an FP insertion, we can decrease the **max_cluster_bias** to avoid these signatures generating an insertion.

Then, regarding the insertion "1021390" in chromosome 1:
Also, as it is shown in the IGV below, the FP insertion is caused by merging excess insertion signatures. And as it is mentioned above, when choosing the median, the position deviates to 1021390. This problem can also be solved by decreasing the **max_cluster_bias**, and the real insertion won't be influenced by excessive signatures.
![image](https://user-images.githubusercontent.com/47966870/180409100-c81def0c-c90f-4848-9807-17672d42c678.png)
In my experiment, when decreasing max_cluster_bias to 100, this two FP insertions will disappear.

So this two parameters can influence our results. According to the design of the parameters, we can achieve some tips for choosing the parameters. The value of the parameters correspond to the **consistence** of the alignment region. When the **consistence** of the sequencing alignment is relatively **high**, we can use a larger parameter like what we set for Hifi in default. To the contrary, when the **consistence** is **low** and the signatures seems to be a little disordered, we can use a smaller parameter like what we set for CLR and ONT.
The default parameters for Hifi, CLR and ONT come from our expereince and work for the global. However, sometimes it doesn't work on all conditions. The high-quality datasets also have chaotic alignment regions and low-quality datasets can have neat alignment regions, too. So in my opinion, it can't be lumped together. For different conditions and datasets characteristics, we may need to make minor adjustments to achieve better results.

All the four examples above are very instructive. Thanks a lot for your clear explanation and the abundant datasets provided for me to make the debug. I hope my explanation is clear and the reply will help you.
If you have any questions or any ideas, don't worry to let me know. 

Best,
Shuqi

**Comment by lxwgcool** [comment]
Thanks so much for your insight Shuqi. It does pretty make sense. I am current re-run these samples in our cluster to see if the performance could be improved significantly. 

Have a great weekend
Best
Xin

**Comment by lxwgcool** [comment]
Hi Shuqi, 

I think we are all set. The new settings work pretty good. I use CLR settings (100, 0.3, 200, 0.5) to run our HiFi Reads. Here is a screenshot of our results: 
![image](https://user-images.githubusercontent.com/11053933/181347496-9459be9e-3a27-4afb-b89c-daa089b36aa6.png)

We prepared the HG002 HiFi reads from our wet lab by combining 3 std input SMRT Cells together. I think it may be a good idea to update the user manual to let people try different parameters if the results are not as good as our expectation. 

Thanks again
Best
Xin

**Comment by tjiangHIT** [comment]
Hello @lxwgcool and @Meltpinkg,

Pretty good results from this detailed and comprehensive discussion.
Thanks for your both great efforts!
This is very exciting.

Cheers，
Tao

**Comment by lxwgcool** [comment]
Hi Shuqi and Tao, 

Sorry for backing to this ticket again. 

We just did an internal group meeting, and we have decided to use cuteSV as one of the SV callers for our in-house pipeline. In order to better understand the algorithm of cuteSV, we have one more question below. 

Regarding using the smaller parameters (max_cluster_bias, same as CLR and ONT we discussed before) instead of higher parameters (as suggested by default) to run our HIFI reads, one of my colleagues posted a question: it does make sense to explain why "higher parameters" brings worse results (incorrect clustering, which cases incorrect position and size of SV). However, why CuteSV suggests use higher parameters to run HiFI Reads while using smaller parameters to run CLR and ONT reads? What benefit we could gain/lose if we use/not use higher parameters to run HiFI Reads? Is there any bad thing may occur if we use smaller parameters to run HiFI Reads?

For my understanding: the reason that cuteSV suggests use smaller/higher parameters is cased by the error rate between CRL/ONT and HiFi is different. Regarding CRL/ONT, since their error rate is high and the high error rate will cause the small offset for the same variant event, that's why the cuteSV suggests use smaller parameters to cluster these same events together. Regarding HIFI, since its error rate is very low and the low error rate won't case the offset for the same variant event, in another word, the same variant event will always occurs at the very close position, that's why cuteSV suggests use the larger parameters to reduce the number of false positive events in final callset (since the two real SV events should has the large gap which won't be clustered even though we use the larger parameters). However, I still have a question: why not still using the "smaller parameters" to handle HIFI reads? Is there any downside if we use "smaller parameters" to handle HIFI reads? If "smaller parameters" fail to cluster some neighbor events together, does it mean these events should be considered both? 

Thanks so much for your help
Looking forward to your comments. 
Best
Xin

**Comment by Meltpinkg** [comment]
Hello Xin

The choosing of the parameter is related to the charateristic of the dataset. In the development of cuteSV, we benchmark it on a well studied sample - HG002 and the parameter carried out the best performance in practice. In theory, the low error rate of HiFi sequencing ensures the separate distance of various SV signatures, while the other sequencing have close confusing signatures. Furthermore, due to the neat signatures, we can apply the cluster in larger range (as for the larger parameter), which can reduce the later compute expense to some extend. Therefore, when the alignment data is neat and of high quality, the larger parameter can achieve the best performance, while the alignments have such close and irregular signatures, the smaller parameter will benefit in this case and won't introduce much drawback.

Best
Shuqi

**Comment by lxwgcool** [comment]
Thanks so much Shuqi, 

I have forwarded your response to my colleague, and here is her response:
```
Thanks Xin!

Is he saying that the main reason you might use the larger cluster distance on HiFi is that 1) it shouldn’t lead to false positives because the alignments should be clean and 2) it results in better compute time?

But let’s say that the alignments ARE clean, but you have 2 separate events that are close together.  Wouldn’t it still potentially try and cluster those together-which would be detrimental?  

I would actually think that when the alignments are noisier (ie, CLR, ONT), THAT would be when the increased cluster difference would be helpful…and might help capture a single event that is represented with noisy, inaccurate alignments at a few different spots.
```

I think my colleague's questions: 
(1) Could you list the major detrimental parts if we use the smaller parameter (max_cluster_bias) to run HIFI reads (disregard the computational performance)? 
(2) Moreover, my colleague think it may be even detrimental if we use larger parameter to process HIFI reads (may potentially try and cluster 2 separate real SV events together). 

I think these are the last two questions we have.
Thanks so much for your help
Best
Xin

**Comment by Meltpinkg** [comment]
Hello, Xin

Sorry for my late reply. The major factor taken into account for designing the parameter is based on our experiments on authoritative datasets. The default parameters outperform in clustering signatures and generating SV breakpoints. 
For the first question, if using smaller parameter on HiFi reads, there would be almost no detrimental parts. And for the next, we are uncertain of the detriment brought by larger parameter, because it depends on the charateristic of the datasets. The large parameter can collect more signatures that deviated by the sequencing and aligning error, however, may lead to the cluster of exceeeding signatures. And the smaller parameter can perform the clustering more precise, while maybe missing several deviated signatures.
It is surely a problem of balance. And from the previous datasets you provided, we think there would be no problem using smaller parameters.

Best,
Shuqi
